name: Update image when Tautulli image updates
on:
  # schedule:
  #   - cron: "0 2 * * *" # everyday at 2am
  workflow_dispatch:

jobs:
  check-base-image:
    outputs:
      baseupdated: ${{ steps.baseupdatecheck.outputs.needs-updating }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: tautulli/tautulli:latest
          image: rickdb/tautulli-plexanisync:latest # update for your image
      - name: No update
        if: ${{ steps.baseupdatecheck.outputs.needs-updating != 'true' }}
        run: echo "No base image update"
      - name: Update found
        if: ${{ steps.baseupdatecheck.outputs.needs-updating == 'true' }}
        run: echo "Base image was updated"

  build-docker-tautulli:
    needs: check-base-image
    if: needs.check-base-image.outputs.baseupdated == 'true'
    uses: ./.github/workflows/build-docker-image.yml
    with:
      dockerfile: ./Docker/Tautulli/Dockerfile
      imagename: ${{ github.repository_owner }}/tautulli-plexanisync
      eventname: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
